### ISSUE TITLE
Lunes Platform

### ISSUE THREAD

**Issue by olivmath** [rust-br/eu-uso-rust#5]
# Estamos usando Rust!

Mais especificamente uma refatoração de uma lib legada em [JS](https://www.npmjs.com/package/lunes-js-api), para poder manter a usabilidade e ter alguns ganhos que o rust nos dá estamos escrevendo em rust e fazendo o *build* para WebAssembly (wasm).

# Lunes Platform
 - https://https://blockchain.lunes.io/telescope/
 - https://github.com/lunes-platform
 - https://lunes.io

**Comment by marioidival** [comment]
Oba! Dale @olivmath 
se quiseres, pode criar um PR para adicionar no repositorio?

**Comment by olivmath** [comment]
Feito!
